# Try e Except: Tratar erros
try:
    numero = int(input("Digite um número: "))
    print(f"Você digitou: {numero} ")
except ValueError:
    print("Erro!!! Digite um número!")
    
# numero1 = int(input("Digite um número: "))
# print(f"Você digitou: {numero1} ")

